#!/usr/bin/env bash
# Writes _data/lastmod.yml: the date each page file last changed, from git
# history, for sitemap.xml's <lastmod>. Run by the build workflow before
# Jekyll (needs full history: checkout with fetch-depth: 0). The file is
# generated, never committed (.gitignore). Usage: bash _tools/lastmod.sh
set -euo pipefail
out=_data/lastmod.yml
{
  echo "# Generated by _tools/lastmod.sh at build time. Do not edit or commit."
  git ls-files '*.html' | grep -v -E '^_|/_' | while read -r f; do
    d=$(git log -1 --format=%cs -- "$f")
    [ -n "$d" ] && printf '"%s": "%s"\n' "$f" "$d"
  done
} > "$out"
echo "lastmod: $(($(wc -l < "$out") - 1)) pages dated"
